### ISSUE TITLE
Change naming convention?

### ISSUE THREAD

**Issue by ergonomicus** [hivokas/laravel-handlers#3]
Just a proposal, for a small project maybe it would be better to name handlers PostIndex, PostCreate, PostUpdate etc.

They would then be easier to find if they all reside in the same namespace/folder...

**Comment by hivokas** [comment]
In this case, I think it would be better to simply create these handlers in a different namespace:

```php
php artisan make:handler Post --resource --namespace=Post
```

**Comment by ergonomicus** [comment]
@hivokas Sure, but that means you need to create namespace for both small and big apps. In that case namespace should be default option, without '--namespace=Post'...

**Comment by hivokas** [comment]
Why not separate the groups of handlers with different namespaces for both small and large applications?

**Comment by ergonomicus** [comment]
As I said, I'm lazy, and I would probably have all my handlers in same namespace (folder) for smaller apps, testing, demos etc.
In that case it would be useful to have handlers prefixed with model name (PostIndex, PostCreate, PostUpdate etc.)

I agree that it is much better to have separate namespace for each model.
In that case naming isn't really important, but then, I think, the default behavior should be to create namespaces and folders automatically, without passing any option (--namespace=Post).
If someone needs handlers without namespaces, then he might pass an option `--without-namespace` or something like that...

Just my thoughts, anyway...

**Comment by hivokas** [comment]
Thanks for the proposals! I will think about both of them.

**Comment by crnkovic** [comment]
I don't agree with this proposal. Handler is a class that performs one action. What is that action? create a post, update a post, right? So the class name should explain what this handler does.

e.g.

`UpdateSubscription`, `BanUser`, `UpdatePost`, ... However, this just seems like a place to namespace: `Posts\\Update`
