### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by shadoWalker89** [hivokas/laravel-handlers#9]
Hi,
First of all sorry if this is not the place to ask the question. My question is

Why use this package instead of using the laravel single action controller with the __invoke() method.
If i'm not wrong all the handlers does is mimic the laravel single action controller.

**Comment by hivokas** [comment]
This package adds a handy way of creating the request handlers. Using flags, you can easily generate multiple request handlers simultaneously, rather than creating them separately.

Also this package adds simple a simple implementation of the request handler that extends the controller and allows you to call only the `__invoke` method from your routing.

**Comment by shadoWalker89** [comment]
Yeah i already checked to code before creating this issue, and i saw that you are extending the laravel controller.
After all the Handler is a controller named Handler instead of controller. It doesn't add new features or helpers.
Do you plan on adding more features later ?
If not, why not just call them controllers and the package would be just a package that adds commands to easily generate different controllers in the same way you are doing it now.

When i read the laravel news blog post and then your package documentation, i kept looking for what these handlers offers that the controllers doesn't already do, so i went i took a look at the source code and found that they are just controllers, and that is why i posted this issue. I wanted to hear from if there is plans on adding features to these handlers ...

Please forgive me if my response feels blunt.
Good luck with your package and thank you for sharing your hard work with the rest of the world.
